### ISSUE TITLE
stm32duino

### ISSUE THREAD

**Issue by ljubomirb** [Floessie/frt#4]
Any chance this will work with stm32, like stm32doino?
I tried removing `#include <Arduino_FreeRTOS.h>` and renaming some taskEnter.... but at one point I realized I am just frantically renaming stuff not knowing what I do. 
Your library, as oppose to other similar, has great documentation with lot of effort put into it, and it would be nice if it development does not stop, so it can be used on other systems like stm32.

**Comment by Floessie** [comment]
Hi Ljubomir,

First of all: thanks for your interest in `frt`. :+1: 

> Your library, as oppose to other similar, has great documentation with lot of effort put into it, and it would be nice if it development does not stop, so it can be used on other systems like stm32.

Well, development hasn't really stopped. It's rather feature complete from my current point of view. But if there are some obstacles for users, I will sure care about them (when time permits, of course). As to the STM32: I only have different AVRs here to test.

> I tried removing `#include <Arduino_FreeRTOS.h>` and renaming some taskEnter.... but at one point I realized I am just frantically renaming stuff not knowing what I do.

Which FreeRTOS port are you using? Shouldn't be too hard to adapt `frt` to it, as it only uses the basic FreeRTOS functions and nothing Arduino specific (apart from `max()` which can be easily implemented).

Best,
Flössie

**Comment by Floessie** [comment]
@ljubomirb FYI, `frt` is now independent of the Arduino_FreeRTOS_library and can be used with the [FreeRTOS kernel](https://github.com/FreeRTOS/FreeRTOS-Kernel).
