### ISSUE TITLE
Problem calling repeatedly a task to run once each time

### ISSUE THREAD

**Issue by fletchjp** [Floessie/frt#5]
Hi. I have been writing an example where a task runs and looks out for repeated input from another Arduino using RS485. When the input is received, it starts another task to flash the inboard LED for 500 ms. This runs fine on Arduino FreeRTOS when the second task finishes with vTaskDelete(). When I try this with frt with the task returning false as suggested.  After a few flashes the code fails with the stack full. I have found that there is a call to vTaskDelete in the code of entryPoint (line 254 in frt.h). It seems that this is not being called. I found that the problem does not occur when the second task is called repeatedly from within loop().

I have codes available on GitHub e.g. 

https://github.com/fletchjp/MERG-Arduino-Software/tree/master/ArduinosConnectedTogether/RS485Examples/DFRobot/RS485ReceivingDataFRT4

https://github.com/fletchjp/MERG-Arduino-Software/tree/master/ArduinosConnectedTogether/RS485Examples/DFRobot/RS485ReceivingDataFreeRTOS2

John Fletcher

**Comment by fletchjp** [comment]
This is very odd. I have constructed another example which does work. I think it is likely that the problem is something I have done. I just have not found it yet.

I have now found the difference. I needed to put an msleep(100,remainder) into the calling task to give the memory task time to run.

**Comment by Floessie** [comment]
@fletchjp Hi John,

I'm glad you found the issue in your code. Dealing with RT tasks is often tricky. Good luck and happy new year!

Best,
Flössie
